/*
 * +-------------------------------------------------------------------+
 * | (C) Copyright IBM Corp. 2025, 2026                                |
 * | SPDX-License-Identifier: Apache-2.0                               |
 * +-------------------------------------------------------------------+
 */

package reporter

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"fmt"
	"os"
	"time"

	cardhealth "github.com/ibm-aiu/spyre-health-checker/pkg/cardhealth"
	pb "github.com/ibm-aiu/spyre-health-checker/pkg/health/spyre"
	types "github.com/ibm-aiu/spyre-health-checker/pkg/types"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
)

const defaultCardHealthTimeout = 10 * time.Second

// CardHealthClient dials the co-located aiu-cardmgmt-health-api sidecar over
// its UNIX socket and queries per-slot health via GetCardHealth using mTLS.
type CardHealthClient struct {
	socketPath  string
	timeout     time.Duration
	tlsCertPath string
	tlsKeyPath  string
	tlsCAPath   string
	// tlsServerName overrides the TLS server-name check. When left empty the
	// Go TLS stack uses the connection address (which is meaningless for a UNIX
	// socket), so callers should supply the CN / SAN that the server cert was
	// issued to (e.g. "spyre-components").
	tlsServerName string
	// debug enables per-slot gRPC call logging to stdout.
	debug bool
}

// NewCardHealthClient returns a CardHealthClient that dials the given UNIX
// socket path with mutual TLS. tlsCertPath / tlsKeyPath are the client
// certificate and private key; tlsCAPath is the CA certificate used to
// verify the server. tlsServerName must match a SAN or CN in the server's
// certificate (use "spyre-components" for certs generated by
// hack/gen-local-certs.sh).
func NewCardHealthClient(socketPath, tlsCertPath, tlsKeyPath, tlsCAPath, tlsServerName string) *CardHealthClient {
	return &CardHealthClient{
		socketPath:    socketPath,
		timeout:       defaultCardHealthTimeout,
		tlsCertPath:   tlsCertPath,
		tlsKeyPath:    tlsKeyPath,
		tlsCAPath:     tlsCAPath,
		tlsServerName: tlsServerName,
	}
}

// SetDebug enables or disables per-slot gRPC call logging. When enabled every
// GetCardHealth call is logged to stdout showing the slot, the raw response
// health string, any application-level error code, and any RPC-level error.
// This is intended for manual troubleshooting (--debug flag) only.
func (c *CardHealthClient) SetDebug(enabled bool) {
	c.debug = enabled
}

// buildMTLSCredentials loads the client cert/key and CA cert from disk and
// returns gRPC transport credentials configured for mutual TLS.
func (c *CardHealthClient) buildMTLSCredentials() (credentials.TransportCredentials, error) {
	cert, err := tls.LoadX509KeyPair(c.tlsCertPath, c.tlsKeyPath)
	if err != nil {
		return nil, fmt.Errorf("cardhealth: load client cert/key: %w", err)
	}
	caPEM, err := os.ReadFile(c.tlsCAPath)
	if err != nil {
		return nil, fmt.Errorf("cardhealth: read CA cert: %w", err)
	}
	caPool := x509.NewCertPool()
	if !caPool.AppendCertsFromPEM(caPEM) {
		return nil, fmt.Errorf("cardhealth: no valid CA certificate found in %s", c.tlsCAPath)
	}
	tlsCfg := &tls.Config{
		Certificates: []tls.Certificate{cert},
		RootCAs:      caPool,
		ServerName:   c.tlsServerName,
		MinVersion:   tls.VersionTLS12,
	}
	return credentials.NewTLS(tlsCfg), nil
}

// CollectForSlots dials the sidecar over mTLS, calls GetCardHealth for each
// PCI slot, and returns a DeviceState per slot. Slots that return an RPC
// error or a non-empty error_code from the sidecar are skipped so that a
// single unavailable slot does not abort the whole collect cycle.
func (c *CardHealthClient) CollectForSlots(slots []string) ([]types.DeviceState, error) {
	creds, err := c.buildMTLSCredentials()
	if err != nil {
		return nil, err
	}
	conn, err := grpc.NewClient("unix://"+c.socketPath, grpc.WithTransportCredentials(creds))
	if err != nil {
		return nil, fmt.Errorf("cardhealth: dial %s: %w", c.socketPath, err)
	}
	defer conn.Close() //nolint:errcheck

	stub := cardhealth.NewCardHealthClient(conn)
	ctx, cancel := context.WithTimeout(context.Background(), c.timeout)
	defer cancel()

	if c.debug {
		fmt.Printf("cardhealth-debug: dialing %s with %d slot(s)\n", c.socketPath, len(slots))
	}

	var firstRPCErr error
	var firstSidecarErr string
	states := make([]types.DeviceState, 0, len(slots))
	for _, slot := range slots {
		resp, err := stub.GetCardHealth(ctx, &cardhealth.GetCardHealthRequest{PciSlot: slot})
		if err != nil {
			// RPC-level failure — record the first occurrence for the summary
			// warning, then skip and continue so one bad slot doesn't abort
			// the whole cycle.
			if firstRPCErr == nil {
				firstRPCErr = err
			}
			if c.debug {
				fmt.Printf("cardhealth-debug: slot %-16s  RPC error: %v\n", slot, err)
			}
			continue
		}
		if resp.Error != nil && resp.Error.ErrorCode != "" {
			// Application-level error reported by the sidecar — skip.
			if firstSidecarErr == "" {
				firstSidecarErr = fmt.Sprintf("code=%s msg=%s", resp.Error.ErrorCode, resp.Error.ErrorMessage)
			}
			if c.debug {
				fmt.Printf("cardhealth-debug: slot %-16s  sidecar error: code=%s msg=%s\n",
					slot, resp.Error.ErrorCode, resp.Error.ErrorMessage)
			}
			continue
		}
		state := pb.DEVICE_STATE_IN_ERROR
		if resp.Health == "healthy" {
			state = pb.DEVICE_STATE_ONLINE
		}
		if c.debug {
			fmt.Printf("cardhealth-debug: slot %-16s  health=%-9s  state=%s\n",
				slot, resp.Health, state)
		}
		states = append(states, types.DeviceState{
			PciAddress: slot,
			Type:       pb.DEVICE_TYPE_PF,
			State:      state,
		})
	}

	// Always emit a single summary warning when errors occurred, even without
	// --debug. This makes systematic failures (e.g. Unauthenticated on every
	// slot) visible in normal logs without flooding them with per-slot lines.
	skipped := len(slots) - len(states)
	if skipped > 0 {
		switch {
		case firstRPCErr != nil:
			fmt.Printf("cardhealth: %d/%d slot(s) skipped — RPC error (first: %v)\n",
				skipped, len(slots), firstRPCErr)
		case firstSidecarErr != "":
			fmt.Printf("cardhealth: %d/%d slot(s) skipped — sidecar error (first: %s)\n",
				skipped, len(slots), firstSidecarErr)
		}
	}

	if c.debug {
		fmt.Printf("cardhealth-debug: collect complete — %d/%d slots returned a state\n",
			len(states), len(slots))
	}

	return states, nil
}
