// (C) Copyright IBM Corp. 2025, 2026
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// Temporary compilation stub — overwritten by `buf generate`.
// source: cardhealth.proto

package cardhealth

import (
	"context"

	"google.golang.org/grpc"
)

// CardHealthClient is the client API for the CardHealth service.
type CardHealthClient interface {
	GetCardHealth(ctx context.Context, in *GetCardHealthRequest, opts ...grpc.CallOption) (*GetCardHealthResponse, error)
	CollectFlightLogsForCard(ctx context.Context, in *CollectFlightLogsRequest, opts ...grpc.CallOption) (*CollectFlightLogsResponse, error)
	GetFlightLogResultsForCard(ctx context.Context, in *GetFlightLogResultsRequest, opts ...grpc.CallOption) (*GetFlightLogResultsResponse, error)
}

type cardHealthClient struct {
	cc grpc.ClientConnInterface
}

// NewCardHealthClient returns a new CardHealthClient backed by cc.
func NewCardHealthClient(cc grpc.ClientConnInterface) CardHealthClient {
	return &cardHealthClient{cc}
}

func (c *cardHealthClient) GetCardHealth(ctx context.Context, in *GetCardHealthRequest, opts ...grpc.CallOption) (*GetCardHealthResponse, error) {
	out := new(GetCardHealthResponse)
	err := c.cc.Invoke(ctx, "/cardhealth.CardHealth/GetCardHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardHealthClient) CollectFlightLogsForCard(ctx context.Context, in *CollectFlightLogsRequest, opts ...grpc.CallOption) (*CollectFlightLogsResponse, error) {
	out := new(CollectFlightLogsResponse)
	err := c.cc.Invoke(ctx, "/cardhealth.CardHealth/CollectFlightLogsForCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardHealthClient) GetFlightLogResultsForCard(ctx context.Context, in *GetFlightLogResultsRequest, opts ...grpc.CallOption) (*GetFlightLogResultsResponse, error) {
	out := new(GetFlightLogResultsResponse)
	err := c.cc.Invoke(ctx, "/cardhealth.CardHealth/GetFlightLogResultsForCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CardHealthServer is the server API for the CardHealth service.
type CardHealthServer interface {
	GetCardHealth(context.Context, *GetCardHealthRequest) (*GetCardHealthResponse, error)
	CollectFlightLogsForCard(context.Context, *CollectFlightLogsRequest) (*CollectFlightLogsResponse, error)
	GetFlightLogResultsForCard(context.Context, *GetFlightLogResultsRequest) (*GetFlightLogResultsResponse, error)
}

// UnimplementedCardHealthServer must be embedded to have forward-compatible implementations.
type UnimplementedCardHealthServer struct{}

func (UnimplementedCardHealthServer) GetCardHealth(context.Context, *GetCardHealthRequest) (*GetCardHealthResponse, error) {
	return nil, nil
}
func (UnimplementedCardHealthServer) CollectFlightLogsForCard(context.Context, *CollectFlightLogsRequest) (*CollectFlightLogsResponse, error) {
	return nil, nil
}
func (UnimplementedCardHealthServer) GetFlightLogResultsForCard(context.Context, *GetFlightLogResultsRequest) (*GetFlightLogResultsResponse, error) {
	return nil, nil
}

// RegisterCardHealthServer registers the CardHealthServer with the gRPC server.
func RegisterCardHealthServer(s *grpc.Server, srv CardHealthServer) {
	s.RegisterService(&_CardHealth_serviceDesc, srv)
}

var _CardHealth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cardhealth.CardHealth",
	HandlerType: (*CardHealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCardHealth",
			Handler: func(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
				in := new(GetCardHealthRequest)
				if interceptor == nil {
					return srv.(CardHealthServer).GetCardHealth(ctx, in)
				}
				info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/cardhealth.CardHealth/GetCardHealth"}
				handler := func(ctx context.Context, req interface{}) (interface{}, error) {
					return srv.(CardHealthServer).GetCardHealth(ctx, req.(*GetCardHealthRequest))
				}
				return interceptor(ctx, in, info, handler)
			},
		},
		{
			MethodName: "CollectFlightLogsForCard",
			Handler: func(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
				in := new(CollectFlightLogsRequest)
				if interceptor == nil {
					return srv.(CardHealthServer).CollectFlightLogsForCard(ctx, in)
				}
				info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/cardhealth.CardHealth/CollectFlightLogsForCard"}
				handler := func(ctx context.Context, req interface{}) (interface{}, error) {
					return srv.(CardHealthServer).CollectFlightLogsForCard(ctx, req.(*CollectFlightLogsRequest))
				}
				return interceptor(ctx, in, info, handler)
			},
		},
		{
			MethodName: "GetFlightLogResultsForCard",
			Handler: func(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
				in := new(GetFlightLogResultsRequest)
				if interceptor == nil {
					return srv.(CardHealthServer).GetFlightLogResultsForCard(ctx, in)
				}
				info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/cardhealth.CardHealth/GetFlightLogResultsForCard"}
				handler := func(ctx context.Context, req interface{}) (interface{}, error) {
					return srv.(CardHealthServer).GetFlightLogResultsForCard(ctx, req.(*GetFlightLogResultsRequest))
				}
				return interceptor(ctx, in, info, handler)
			},
		},
	},
	Streams: []grpc.StreamDesc{},
}
