// Copyright (c) 2026 IBM Corp.
// SPDX-License-Identifier: Apache-2.0
//
// Card Health gRPC API
// This proto defines a small gRPC interface for the Health API wrapper that
// wraps a subset of a single RPyC-based card management worker running on
// the same node/Pod. There is no `node_name` field on any message: this
// wrapper always talks to exactly one, co-located worker.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: cardhealth.proto

package cardhealth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CardHealth_GetCardHealth_FullMethodName              = "/cardhealth.CardHealth/GetCardHealth"
	CardHealth_CollectFlightLogsForCard_FullMethodName   = "/cardhealth.CardHealth/CollectFlightLogsForCard"
	CardHealth_GetFlightLogResultsForCard_FullMethodName = "/cardhealth.CardHealth/GetFlightLogResultsForCard"
)

// CardHealthClient is the client API for CardHealth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Card Health Service
type CardHealthClient interface {
	// Returns a simplified healthy/unhealthy status for a card, derived from
	// the worker's getCardStatus() result.
	GetCardHealth(ctx context.Context, in *GetCardHealthRequest, opts ...grpc.CallOption) (*GetCardHealthResponse, error)
	// Flight logs operations
	CollectFlightLogsForCard(ctx context.Context, in *CollectFlightLogsRequest, opts ...grpc.CallOption) (*CollectFlightLogsResponse, error)
	GetFlightLogResultsForCard(ctx context.Context, in *GetFlightLogResultsRequest, opts ...grpc.CallOption) (*GetFlightLogResultsResponse, error)
}

type cardHealthClient struct {
	cc grpc.ClientConnInterface
}

func NewCardHealthClient(cc grpc.ClientConnInterface) CardHealthClient {
	return &cardHealthClient{cc}
}

func (c *cardHealthClient) GetCardHealth(ctx context.Context, in *GetCardHealthRequest, opts ...grpc.CallOption) (*GetCardHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCardHealthResponse)
	err := c.cc.Invoke(ctx, CardHealth_GetCardHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardHealthClient) CollectFlightLogsForCard(ctx context.Context, in *CollectFlightLogsRequest, opts ...grpc.CallOption) (*CollectFlightLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectFlightLogsResponse)
	err := c.cc.Invoke(ctx, CardHealth_CollectFlightLogsForCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardHealthClient) GetFlightLogResultsForCard(ctx context.Context, in *GetFlightLogResultsRequest, opts ...grpc.CallOption) (*GetFlightLogResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFlightLogResultsResponse)
	err := c.cc.Invoke(ctx, CardHealth_GetFlightLogResultsForCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CardHealthServer is the server API for CardHealth service.
// All implementations must embed UnimplementedCardHealthServer
// for forward compatibility.
//
// Card Health Service
type CardHealthServer interface {
	// Returns a simplified healthy/unhealthy status for a card, derived from
	// the worker's getCardStatus() result.
	GetCardHealth(context.Context, *GetCardHealthRequest) (*GetCardHealthResponse, error)
	// Flight logs operations
	CollectFlightLogsForCard(context.Context, *CollectFlightLogsRequest) (*CollectFlightLogsResponse, error)
	GetFlightLogResultsForCard(context.Context, *GetFlightLogResultsRequest) (*GetFlightLogResultsResponse, error)
	mustEmbedUnimplementedCardHealthServer()
}

// UnimplementedCardHealthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCardHealthServer struct{}

func (UnimplementedCardHealthServer) GetCardHealth(context.Context, *GetCardHealthRequest) (*GetCardHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCardHealth not implemented")
}
func (UnimplementedCardHealthServer) CollectFlightLogsForCard(context.Context, *CollectFlightLogsRequest) (*CollectFlightLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectFlightLogsForCard not implemented")
}
func (UnimplementedCardHealthServer) GetFlightLogResultsForCard(context.Context, *GetFlightLogResultsRequest) (*GetFlightLogResultsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFlightLogResultsForCard not implemented")
}
func (UnimplementedCardHealthServer) mustEmbedUnimplementedCardHealthServer() {}
func (UnimplementedCardHealthServer) testEmbeddedByValue()                    {}

// UnsafeCardHealthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CardHealthServer will
// result in compilation errors.
type UnsafeCardHealthServer interface {
	mustEmbedUnimplementedCardHealthServer()
}

func RegisterCardHealthServer(s grpc.ServiceRegistrar, srv CardHealthServer) {
	// If the following call panics, it indicates UnimplementedCardHealthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CardHealth_ServiceDesc, srv)
}

func _CardHealth_GetCardHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCardHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardHealthServer).GetCardHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardHealth_GetCardHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardHealthServer).GetCardHealth(ctx, req.(*GetCardHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardHealth_CollectFlightLogsForCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectFlightLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardHealthServer).CollectFlightLogsForCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardHealth_CollectFlightLogsForCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardHealthServer).CollectFlightLogsForCard(ctx, req.(*CollectFlightLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardHealth_GetFlightLogResultsForCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlightLogResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardHealthServer).GetFlightLogResultsForCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardHealth_GetFlightLogResultsForCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardHealthServer).GetFlightLogResultsForCard(ctx, req.(*GetFlightLogResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CardHealth_ServiceDesc is the grpc.ServiceDesc for CardHealth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CardHealth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cardhealth.CardHealth",
	HandlerType: (*CardHealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCardHealth",
			Handler:    _CardHealth_GetCardHealth_Handler,
		},
		{
			MethodName: "CollectFlightLogsForCard",
			Handler:    _CardHealth_CollectFlightLogsForCard_Handler,
		},
		{
			MethodName: "GetFlightLogResultsForCard",
			Handler:    _CardHealth_GetFlightLogResultsForCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cardhealth.proto",
}
