// (C) Copyright IBM Corp. 2025, 2026
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// Temporary compilation stub — overwritten by `buf generate`.
// source: cardhealth.proto

package cardhealth

// ErrorDetails carries an optional application-level error from the sidecar.
type ErrorDetails struct {
	ErrorCode    string
	ErrorMessage string
}

// GetCardHealthRequest is the request message for CardHealth.GetCardHealth.
type GetCardHealthRequest struct {
	PciSlot string
}

// GetCardHealthResponse is the response message for CardHealth.GetCardHealth.
type GetCardHealthResponse struct {
	Health string
	Error  *ErrorDetails
}

// MessageResult carries a category/message pair returned by flight-log RPCs.
type MessageResult struct {
	Category string
	Message  string
}

// CollectFlightLogsRequest is the request for CardHealth.CollectFlightLogsForCard.
type CollectFlightLogsRequest struct {
	PciSlot string
	Kwargs  map[string]string
}

// CollectFlightLogsResponse is the response for CardHealth.CollectFlightLogsForCard.
type CollectFlightLogsResponse struct {
	Result *MessageResult
	Error  *ErrorDetails
}

// GetFlightLogResultsRequest is the request for CardHealth.GetFlightLogResultsForCard.
type GetFlightLogResultsRequest struct {
	PciSlot string
}

// GetFlightLogResultsResponse is the response for CardHealth.GetFlightLogResultsForCard.
type GetFlightLogResultsResponse struct {
	Results []string
	Error   *ErrorDetails
}
