// Copyright (c) 2026 IBM Corp.
// SPDX-License-Identifier: Apache-2.0
//
// Card Health gRPC API
// This proto defines a small gRPC interface for the Health API wrapper that
// wraps a subset of a single RPyC-based card management worker running on
// the same node/Pod. There is no `node_name` field on any message: this
// wrapper always talks to exactly one, co-located worker.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cardhealth.proto

package cardhealth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common message types
type MessageResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResult) Reset() {
	*x = MessageResult{}
	mi := &file_cardhealth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResult) ProtoMessage() {}

func (x *MessageResult) ProtoReflect() protoreflect.Message {
	mi := &file_cardhealth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResult.ProtoReflect.Descriptor instead.
func (*MessageResult) Descriptor() ([]byte, []int) {
	return file_cardhealth_proto_rawDescGZIP(), []int{0}
}

func (x *MessageResult) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MessageResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ErrorDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails) Reset() {
	*x = ErrorDetails{}
	mi := &file_cardhealth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails) ProtoMessage() {}

func (x *ErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_cardhealth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails.ProtoReflect.Descriptor instead.
func (*ErrorDetails) Descriptor() ([]byte, []int) {
	return file_cardhealth_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorDetails) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ErrorDetails) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// GetCardHealth
type GetCardHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PciSlot       string                 `protobuf:"bytes,1,opt,name=pci_slot,json=pciSlot,proto3" json:"pci_slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardHealthRequest) Reset() {
	*x = GetCardHealthRequest{}
	mi := &file_cardhealth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardHealthRequest) ProtoMessage() {}

func (x *GetCardHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cardhealth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardHealthRequest.ProtoReflect.Descriptor instead.
func (*GetCardHealthRequest) Descriptor() ([]byte, []int) {
	return file_cardhealth_proto_rawDescGZIP(), []int{2}
}

func (x *GetCardHealthRequest) GetPciSlot() string {
	if x != nil {
		return x.PciSlot
	}
	return ""
}

type GetCardHealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Simplified status: "healthy" or "unhealthy".
	Health        string        `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`
	Error         *ErrorDetails `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardHealthResponse) Reset() {
	*x = GetCardHealthResponse{}
	mi := &file_cardhealth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardHealthResponse) ProtoMessage() {}

func (x *GetCardHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cardhealth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardHealthResponse.ProtoReflect.Descriptor instead.
func (*GetCardHealthResponse) Descriptor() ([]byte, []int) {
	return file_cardhealth_proto_rawDescGZIP(), []int{3}
}

func (x *GetCardHealthResponse) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *GetCardHealthResponse) GetError() *ErrorDetails {
	if x != nil {
		return x.Error
	}
	return nil
}

// CollectFlightLogsForCard
type CollectFlightLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PciSlot       string                 `protobuf:"bytes,1,opt,name=pci_slot,json=pciSlot,proto3" json:"pci_slot,omitempty"`
	Kwargs        map[string]string      `protobuf:"bytes,2,rep,name=kwargs,proto3" json:"kwargs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectFlightLogsRequest) Reset() {
	*x = CollectFlightLogsRequest{}
	mi := &file_cardhealth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectFlightLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectFlightLogsRequest) ProtoMessage() {}

func (x *CollectFlightLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cardhealth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectFlightLogsRequest.ProtoReflect.Descriptor instead.
func (*CollectFlightLogsRequest) Descriptor() ([]byte, []int) {
	return file_cardhealth_proto_rawDescGZIP(), []int{4}
}

func (x *CollectFlightLogsRequest) GetPciSlot() string {
	if x != nil {
		return x.PciSlot
	}
	return ""
}

func (x *CollectFlightLogsRequest) GetKwargs() map[string]string {
	if x != nil {
		return x.Kwargs
	}
	return nil
}

type CollectFlightLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *MessageResult         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         *ErrorDetails          `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectFlightLogsResponse) Reset() {
	*x = CollectFlightLogsResponse{}
	mi := &file_cardhealth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectFlightLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectFlightLogsResponse) ProtoMessage() {}

func (x *CollectFlightLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cardhealth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectFlightLogsResponse.ProtoReflect.Descriptor instead.
func (*CollectFlightLogsResponse) Descriptor() ([]byte, []int) {
	return file_cardhealth_proto_rawDescGZIP(), []int{5}
}

func (x *CollectFlightLogsResponse) GetResult() *MessageResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CollectFlightLogsResponse) GetError() *ErrorDetails {
	if x != nil {
		return x.Error
	}
	return nil
}

// GetFlightLogResultsForCard
type GetFlightLogResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PciSlot       string                 `protobuf:"bytes,1,opt,name=pci_slot,json=pciSlot,proto3" json:"pci_slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlightLogResultsRequest) Reset() {
	*x = GetFlightLogResultsRequest{}
	mi := &file_cardhealth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlightLogResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlightLogResultsRequest) ProtoMessage() {}

func (x *GetFlightLogResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cardhealth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlightLogResultsRequest.ProtoReflect.Descriptor instead.
func (*GetFlightLogResultsRequest) Descriptor() ([]byte, []int) {
	return file_cardhealth_proto_rawDescGZIP(), []int{6}
}

func (x *GetFlightLogResultsRequest) GetPciSlot() string {
	if x != nil {
		return x.PciSlot
	}
	return ""
}

type GetFlightLogResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []string               `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Error         *ErrorDetails          `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlightLogResultsResponse) Reset() {
	*x = GetFlightLogResultsResponse{}
	mi := &file_cardhealth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlightLogResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlightLogResultsResponse) ProtoMessage() {}

func (x *GetFlightLogResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cardhealth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlightLogResultsResponse.ProtoReflect.Descriptor instead.
func (*GetFlightLogResultsResponse) Descriptor() ([]byte, []int) {
	return file_cardhealth_proto_rawDescGZIP(), []int{7}
}

func (x *GetFlightLogResultsResponse) GetResults() []string {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GetFlightLogResultsResponse) GetError() *ErrorDetails {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_cardhealth_proto protoreflect.FileDescriptor

const file_cardhealth_proto_rawDesc = "" +
	"\n" +
	"\x10cardhealth.proto\x12\n" +
	"cardhealth\"E\n" +
	"\rMessageResult\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"R\n" +
	"\fErrorDetails\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"1\n" +
	"\x14GetCardHealthRequest\x12\x19\n" +
	"\bpci_slot\x18\x01 \x01(\tR\apciSlot\"_\n" +
	"\x15GetCardHealthResponse\x12\x16\n" +
	"\x06health\x18\x01 \x01(\tR\x06health\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x18.cardhealth.ErrorDetailsR\x05error\"\xba\x01\n" +
	"\x18CollectFlightLogsRequest\x12\x19\n" +
	"\bpci_slot\x18\x01 \x01(\tR\apciSlot\x12H\n" +
	"\x06kwargs\x18\x02 \x03(\v20.cardhealth.CollectFlightLogsRequest.KwargsEntryR\x06kwargs\x1a9\n" +
	"\vKwargsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"~\n" +
	"\x19CollectFlightLogsResponse\x121\n" +
	"\x06result\x18\x01 \x01(\v2\x19.cardhealth.MessageResultR\x06result\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x18.cardhealth.ErrorDetailsR\x05error\"7\n" +
	"\x1aGetFlightLogResultsRequest\x12\x19\n" +
	"\bpci_slot\x18\x01 \x01(\tR\apciSlot\"g\n" +
	"\x1bGetFlightLogResultsResponse\x12\x18\n" +
	"\aresults\x18\x01 \x03(\tR\aresults\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x18.cardhealth.ErrorDetailsR\x05error2\xba\x02\n" +
	"\n" +
	"CardHealth\x12T\n" +
	"\rGetCardHealth\x12 .cardhealth.GetCardHealthRequest\x1a!.cardhealth.GetCardHealthResponse\x12g\n" +
	"\x18CollectFlightLogsForCard\x12$.cardhealth.CollectFlightLogsRequest\x1a%.cardhealth.CollectFlightLogsResponse\x12m\n" +
	"\x1aGetFlightLogResultsForCard\x12&.cardhealth.GetFlightLogResultsRequest\x1a'.cardhealth.GetFlightLogResultsResponseB8Z6github.com/ibm-aiu/spyre-health-checker/pkg/cardhealthb\x06proto3"

var (
	file_cardhealth_proto_rawDescOnce sync.Once
	file_cardhealth_proto_rawDescData []byte
)

func file_cardhealth_proto_rawDescGZIP() []byte {
	file_cardhealth_proto_rawDescOnce.Do(func() {
		file_cardhealth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cardhealth_proto_rawDesc), len(file_cardhealth_proto_rawDesc)))
	})
	return file_cardhealth_proto_rawDescData
}

var file_cardhealth_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cardhealth_proto_goTypes = []any{
	(*MessageResult)(nil),               // 0: cardhealth.MessageResult
	(*ErrorDetails)(nil),                // 1: cardhealth.ErrorDetails
	(*GetCardHealthRequest)(nil),        // 2: cardhealth.GetCardHealthRequest
	(*GetCardHealthResponse)(nil),       // 3: cardhealth.GetCardHealthResponse
	(*CollectFlightLogsRequest)(nil),    // 4: cardhealth.CollectFlightLogsRequest
	(*CollectFlightLogsResponse)(nil),   // 5: cardhealth.CollectFlightLogsResponse
	(*GetFlightLogResultsRequest)(nil),  // 6: cardhealth.GetFlightLogResultsRequest
	(*GetFlightLogResultsResponse)(nil), // 7: cardhealth.GetFlightLogResultsResponse
	nil,                                 // 8: cardhealth.CollectFlightLogsRequest.KwargsEntry
}
var file_cardhealth_proto_depIdxs = []int32{
	1, // 0: cardhealth.GetCardHealthResponse.error:type_name -> cardhealth.ErrorDetails
	8, // 1: cardhealth.CollectFlightLogsRequest.kwargs:type_name -> cardhealth.CollectFlightLogsRequest.KwargsEntry
	0, // 2: cardhealth.CollectFlightLogsResponse.result:type_name -> cardhealth.MessageResult
	1, // 3: cardhealth.CollectFlightLogsResponse.error:type_name -> cardhealth.ErrorDetails
	1, // 4: cardhealth.GetFlightLogResultsResponse.error:type_name -> cardhealth.ErrorDetails
	2, // 5: cardhealth.CardHealth.GetCardHealth:input_type -> cardhealth.GetCardHealthRequest
	4, // 6: cardhealth.CardHealth.CollectFlightLogsForCard:input_type -> cardhealth.CollectFlightLogsRequest
	6, // 7: cardhealth.CardHealth.GetFlightLogResultsForCard:input_type -> cardhealth.GetFlightLogResultsRequest
	3, // 8: cardhealth.CardHealth.GetCardHealth:output_type -> cardhealth.GetCardHealthResponse
	5, // 9: cardhealth.CardHealth.CollectFlightLogsForCard:output_type -> cardhealth.CollectFlightLogsResponse
	7, // 10: cardhealth.CardHealth.GetFlightLogResultsForCard:output_type -> cardhealth.GetFlightLogResultsResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_cardhealth_proto_init() }
func file_cardhealth_proto_init() {
	if File_cardhealth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cardhealth_proto_rawDesc), len(file_cardhealth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cardhealth_proto_goTypes,
		DependencyIndexes: file_cardhealth_proto_depIdxs,
		MessageInfos:      file_cardhealth_proto_msgTypes,
	}.Build()
	File_cardhealth_proto = out.File
	file_cardhealth_proto_goTypes = nil
	file_cardhealth_proto_depIdxs = nil
}
