version: 2

run:
  timeout: 10m
  allow-parallel-runners: true

issues:
  # don't exclude the default set of lint
  exclude-use-default: false
  exclude-rules:
  - path: (.+)_test\.go
    linters:
    - lll
    - errcheck
    - goconst

  - path: "cmd/*"
    linters:
    - lll

linters:
  disable-all: false
  enable:
  - dupl
  - errcheck
  - copyloopvar
  - goconst
  - gocyclo
  - govet
  - ineffassign
  - lll
  - misspell
  - nakedret
  - prealloc
  - staticcheck
  - unconvert
  - unparam
  - unused
  - gocritic

formatters:
  enable:
  - gofmt
  - goimports

linters-settings:
  lll:
    line-length: 140
