default_install_hook_types:
- pre-commit
default_stages:
- pre-commit
fail_fast: true
exclude: boilerplate\..*|.*\.gen\..*|.*\.gotmpl$
repos:
- repo: https://github.com/tekwizely/pre-commit-golang
  rev: v1.0.0-rc.2
  hooks:
  - id: go-fmt
  - id: go-mod-tidy
- repo: local
  hooks:
  - id: golangci-lint
    name: golangci-lint
    entry: make lint-fix
    language: system
    pass_filenames: false
  - id: protoc
    name: protoc
    entry: make protoc-gen
    language: system
    pass_filenames: false
- repo: https://github.com/google/yamlfmt
  rev: v0.17.2
  hooks:
  - id: yamlfmt
    args: ["-dstar", "-conf=.yamlfmt"]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-merge-conflict
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-json
    exclude: pkg/spyredevice/config/test-template/wrong-format/senlib_config.json
  - id: check-yaml
    args:
    - --allow-multiple-documents
    exclude: (document)/.*\.(yaml|yml)
  - id: check-symlinks
  - id: check-added-large-files
  - id: trailing-whitespace
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: ["--fix=lf"]
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    args: [--write-changes]
- repo: https://github.com/pecigonzalo/pre-commit-shfmt
  rev: v2.2.0
  hooks:
  - id: shell-fmt-go
    args:
    - -w
    - -s
    - -l
