# Format is $GHE_ORG_ID-$GHE_REPO_ID
sonar.projectKey=288887-1862134
# Format is $GHE_ORG_NAME/$GHE_ORG_REPO
sonar.projectName=ai-foundation/spyre-health-checker
# SonarQube Host URL
sonar.host.url=https://sonarqube-prod.apps.wdc-sonarqube-prod.core.cirrus.ibm.com
# SonarQube exclustions
sonar.exclusions=**/docs/**,**/jenkins/**,**/test/manifest/**,**/hack/**
