// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: pkg/proto/spyre_health/spyre_health.proto

package spyre

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SpyreHealthService_RegisterForSpyreDevicesEvents_FullMethodName = "/SpyreHealthService/RegisterForSpyreDevicesEvents"
)

// SpyreHealthServiceClient is the client API for SpyreHealthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpyreHealthServiceClient interface {
	// RegisterForSpyreDevicesEvents returns a stream of Devices messages on the change of state of
	// the devices present in on the nodes
	RegisterForSpyreDevicesEvents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (SpyreHealthService_RegisterForSpyreDevicesEventsClient, error)
}

type spyreHealthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpyreHealthServiceClient(cc grpc.ClientConnInterface) SpyreHealthServiceClient {
	return &spyreHealthServiceClient{cc}
}

func (c *spyreHealthServiceClient) RegisterForSpyreDevicesEvents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (SpyreHealthService_RegisterForSpyreDevicesEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SpyreHealthService_ServiceDesc.Streams[0], SpyreHealthService_RegisterForSpyreDevicesEvents_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &spyreHealthServiceRegisterForSpyreDevicesEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SpyreHealthService_RegisterForSpyreDevicesEventsClient interface {
	Recv() (*Devices, error)
	grpc.ClientStream
}

type spyreHealthServiceRegisterForSpyreDevicesEventsClient struct {
	grpc.ClientStream
}

func (x *spyreHealthServiceRegisterForSpyreDevicesEventsClient) Recv() (*Devices, error) {
	m := new(Devices)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SpyreHealthServiceServer is the server API for SpyreHealthService service.
// All implementations must embed UnimplementedSpyreHealthServiceServer
// for forward compatibility
type SpyreHealthServiceServer interface {
	// RegisterForSpyreDevicesEvents returns a stream of Devices messages on the change of state of
	// the devices present in on the nodes
	RegisterForSpyreDevicesEvents(*emptypb.Empty, SpyreHealthService_RegisterForSpyreDevicesEventsServer) error
	mustEmbedUnimplementedSpyreHealthServiceServer()
}

// UnimplementedSpyreHealthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSpyreHealthServiceServer struct {
}

func (UnimplementedSpyreHealthServiceServer) RegisterForSpyreDevicesEvents(*emptypb.Empty, SpyreHealthService_RegisterForSpyreDevicesEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method RegisterForSpyreDevicesEvents not implemented")
}
func (UnimplementedSpyreHealthServiceServer) mustEmbedUnimplementedSpyreHealthServiceServer() {}

// UnsafeSpyreHealthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpyreHealthServiceServer will
// result in compilation errors.
type UnsafeSpyreHealthServiceServer interface {
	mustEmbedUnimplementedSpyreHealthServiceServer()
}

func RegisterSpyreHealthServiceServer(s grpc.ServiceRegistrar, srv SpyreHealthServiceServer) {
	s.RegisterService(&SpyreHealthService_ServiceDesc, srv)
}

func _SpyreHealthService_RegisterForSpyreDevicesEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SpyreHealthServiceServer).RegisterForSpyreDevicesEvents(m, &spyreHealthServiceRegisterForSpyreDevicesEventsServer{stream})
}

type SpyreHealthService_RegisterForSpyreDevicesEventsServer interface {
	Send(*Devices) error
	grpc.ServerStream
}

type spyreHealthServiceRegisterForSpyreDevicesEventsServer struct {
	grpc.ServerStream
}

func (x *spyreHealthServiceRegisterForSpyreDevicesEventsServer) Send(m *Devices) error {
	return x.ServerStream.SendMsg(m)
}

// SpyreHealthService_ServiceDesc is the grpc.ServiceDesc for SpyreHealthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpyreHealthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SpyreHealthService",
	HandlerType: (*SpyreHealthServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterForSpyreDevicesEvents",
			Handler:       _SpyreHealthService_RegisterForSpyreDevicesEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/proto/spyre_health/spyre_health.proto",
}
