// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: spyre_health.proto

package spyre

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpyreHealthService_RegisterForSpyreDevicesEvents_FullMethodName = "/SpyreHealthService/RegisterForSpyreDevicesEvents"
)

// SpyreHealthServiceClient is the client API for SpyreHealthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SpyreHealthService provides the necessary endpoints to:
// - Get the list of IBM Spyre Devices present on the host and their state
type SpyreHealthServiceClient interface {
	// RegisterForSpyreDevicesEvents returns a stream of Devices messages on the change of state of
	// the devices present in on the nodes
	RegisterForSpyreDevicesEvents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Devices], error)
}

type spyreHealthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpyreHealthServiceClient(cc grpc.ClientConnInterface) SpyreHealthServiceClient {
	return &spyreHealthServiceClient{cc}
}

func (c *spyreHealthServiceClient) RegisterForSpyreDevicesEvents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Devices], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SpyreHealthService_ServiceDesc.Streams[0], SpyreHealthService_RegisterForSpyreDevicesEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, Devices]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpyreHealthService_RegisterForSpyreDevicesEventsClient = grpc.ServerStreamingClient[Devices]

// SpyreHealthServiceServer is the server API for SpyreHealthService service.
// All implementations must embed UnimplementedSpyreHealthServiceServer
// for forward compatibility.
//
// SpyreHealthService provides the necessary endpoints to:
// - Get the list of IBM Spyre Devices present on the host and their state
type SpyreHealthServiceServer interface {
	// RegisterForSpyreDevicesEvents returns a stream of Devices messages on the change of state of
	// the devices present in on the nodes
	RegisterForSpyreDevicesEvents(*emptypb.Empty, grpc.ServerStreamingServer[Devices]) error
	mustEmbedUnimplementedSpyreHealthServiceServer()
}

// UnimplementedSpyreHealthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpyreHealthServiceServer struct{}

func (UnimplementedSpyreHealthServiceServer) RegisterForSpyreDevicesEvents(*emptypb.Empty, grpc.ServerStreamingServer[Devices]) error {
	return status.Error(codes.Unimplemented, "method RegisterForSpyreDevicesEvents not implemented")
}
func (UnimplementedSpyreHealthServiceServer) mustEmbedUnimplementedSpyreHealthServiceServer() {}
func (UnimplementedSpyreHealthServiceServer) testEmbeddedByValue()                            {}

// UnsafeSpyreHealthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpyreHealthServiceServer will
// result in compilation errors.
type UnsafeSpyreHealthServiceServer interface {
	mustEmbedUnimplementedSpyreHealthServiceServer()
}

func RegisterSpyreHealthServiceServer(s grpc.ServiceRegistrar, srv SpyreHealthServiceServer) {
	// If the following call panics, it indicates UnimplementedSpyreHealthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpyreHealthService_ServiceDesc, srv)
}

func _SpyreHealthService_RegisterForSpyreDevicesEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SpyreHealthServiceServer).RegisterForSpyreDevicesEvents(m, &grpc.GenericServerStream[emptypb.Empty, Devices]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpyreHealthService_RegisterForSpyreDevicesEventsServer = grpc.ServerStreamingServer[Devices]

// SpyreHealthService_ServiceDesc is the grpc.ServiceDesc for SpyreHealthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpyreHealthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SpyreHealthService",
	HandlerType: (*SpyreHealthServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterForSpyreDevicesEvents",
			Handler:       _SpyreHealthService_RegisterForSpyreDevicesEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "spyre_health.proto",
}
