// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: pkg/proto/spyre_health/spyre_health.proto

package spyre

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DEVICE_TYPE defines the device type
type DEVICE_TYPE int32

const (
	DEVICE_TYPE_DEVICE_TYPE_UNSPECIFIED DEVICE_TYPE = 0 // Reserving message ID 0
	DEVICE_TYPE_VF                      DEVICE_TYPE = 1 // A VF device
	DEVICE_TYPE_PF                      DEVICE_TYPE = 2 // A PF device
)

// Enum value maps for DEVICE_TYPE.
var (
	DEVICE_TYPE_name = map[int32]string{
		0: "DEVICE_TYPE_UNSPECIFIED",
		1: "VF",
		2: "PF",
	}
	DEVICE_TYPE_value = map[string]int32{
		"DEVICE_TYPE_UNSPECIFIED": 0,
		"VF":                      1,
		"PF":                      2,
	}
)

func (x DEVICE_TYPE) Enum() *DEVICE_TYPE {
	p := new(DEVICE_TYPE)
	*p = x
	return p
}

func (x DEVICE_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DEVICE_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_spyre_health_spyre_health_proto_enumTypes[0].Descriptor()
}

func (DEVICE_TYPE) Type() protoreflect.EnumType {
	return &file_pkg_proto_spyre_health_spyre_health_proto_enumTypes[0]
}

func (x DEVICE_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DEVICE_TYPE.Descriptor instead.
func (DEVICE_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_spyre_health_spyre_health_proto_rawDescGZIP(), []int{0}
}

// DEVICE_STATE defines the device state
type DEVICE_STATE int32

const (
	DEVICE_STATE_DEVICE_STATE_UNSPECIFIED DEVICE_STATE = 0 // Reserving message ID 0
	DEVICE_STATE_OFFLINE                  DEVICE_STATE = 1 // The device is in offline state, it has not been booted or it
	// has been shutdown
	DEVICE_STATE_BOOTING DEVICE_STATE = 2 // The device is in the booting (starting) state, with the
	// initialization being complete
	DEVICE_STATE_SHUTTING_DOWN       DEVICE_STATE = 3 // The device is in the process of shutting down
	DEVICE_STATE_ONLINE              DEVICE_STATE = 4 // The device initialization is complete
	DEVICE_STATE_RUNNING_DIAGNOSTICS DEVICE_STATE = 5 // The device is a running diagnostics
	DEVICE_STATE_IN_ERROR            DEVICE_STATE = 6 // The device is a non-running state
)

// Enum value maps for DEVICE_STATE.
var (
	DEVICE_STATE_name = map[int32]string{
		0: "DEVICE_STATE_UNSPECIFIED",
		1: "OFFLINE",
		2: "BOOTING",
		3: "SHUTTING_DOWN",
		4: "ONLINE",
		5: "RUNNING_DIAGNOSTICS",
		6: "IN_ERROR",
	}
	DEVICE_STATE_value = map[string]int32{
		"DEVICE_STATE_UNSPECIFIED": 0,
		"OFFLINE":                  1,
		"BOOTING":                  2,
		"SHUTTING_DOWN":            3,
		"ONLINE":                   4,
		"RUNNING_DIAGNOSTICS":      5,
		"IN_ERROR":                 6,
	}
)

func (x DEVICE_STATE) Enum() *DEVICE_STATE {
	p := new(DEVICE_STATE)
	*p = x
	return p
}

func (x DEVICE_STATE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DEVICE_STATE) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_spyre_health_spyre_health_proto_enumTypes[1].Descriptor()
}

func (DEVICE_STATE) Type() protoreflect.EnumType {
	return &file_pkg_proto_spyre_health_spyre_health_proto_enumTypes[1]
}

func (x DEVICE_STATE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DEVICE_STATE.Descriptor instead.
func (DEVICE_STATE) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_spyre_health_spyre_health_proto_rawDescGZIP(), []int{1}
}

// Device defines an AIU device with its ID (PCI buses address),
// type (VF or PF), state and manager process id.
type Device struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceID         *DeviceID              `protobuf:"bytes,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`                          // The ID of the device
	DeviceType       DEVICE_TYPE            `protobuf:"varint,2,opt,name=deviceType,proto3,enum=DEVICE_TYPE" json:"deviceType,omitempty"`    // The type of device
	DeviceState      DEVICE_STATE           `protobuf:"varint,3,opt,name=deviceState,proto3,enum=DEVICE_STATE" json:"deviceState,omitempty"` // The device state
	ManagerProcessID int64                  `protobuf:"varint,4,opt,name=managerProcessID,proto3" json:"managerProcessID,omitempty"`         // Unix process id of the manager process
	UpdateTimestamp  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updateTimestamp,proto3" json:"updateTimestamp,omitempty"`            // The last state update timestamp
}

func (x *Device) Reset() {
	*x = Device{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_spyre_health_spyre_health_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_spyre_health_spyre_health_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_pkg_proto_spyre_health_spyre_health_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetDeviceID() *DeviceID {
	if x != nil {
		return x.DeviceID
	}
	return nil
}

func (x *Device) GetDeviceType() DEVICE_TYPE {
	if x != nil {
		return x.DeviceType
	}
	return DEVICE_TYPE_DEVICE_TYPE_UNSPECIFIED
}

func (x *Device) GetDeviceState() DEVICE_STATE {
	if x != nil {
		return x.DeviceState
	}
	return DEVICE_STATE_DEVICE_STATE_UNSPECIFIED
}

func (x *Device) GetManagerProcessID() int64 {
	if x != nil {
		return x.ManagerProcessID
	}
	return 0
}

func (x *Device) GetUpdateTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTimestamp
	}
	return nil
}

// Devices defines a collection of devices
type Devices struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Devices []*Device `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
}

func (x *Devices) Reset() {
	*x = Devices{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_spyre_health_spyre_health_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Devices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Devices) ProtoMessage() {}

func (x *Devices) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_spyre_health_spyre_health_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Devices.ProtoReflect.Descriptor instead.
func (*Devices) Descriptor() ([]byte, []int) {
	return file_pkg_proto_spyre_health_spyre_health_proto_rawDescGZIP(), []int{1}
}

func (x *Devices) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

// DeviceID defines the device id (pci address)
type DeviceID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PCIAddress string `protobuf:"bytes,1,opt,name=PCIAddress,proto3" json:"PCIAddress,omitempty"`
}

func (x *DeviceID) Reset() {
	*x = DeviceID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_spyre_health_spyre_health_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceID) ProtoMessage() {}

func (x *DeviceID) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_spyre_health_spyre_health_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceID.ProtoReflect.Descriptor instead.
func (*DeviceID) Descriptor() ([]byte, []int) {
	return file_pkg_proto_spyre_health_spyre_health_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceID) GetPCIAddress() string {
	if x != nil {
		return x.PCIAddress
	}
	return ""
}

var File_pkg_proto_spyre_health_spyre_health_proto protoreflect.FileDescriptor

var file_pkg_proto_spyre_health_spyre_health_proto_rawDesc = []byte{
	0x0a, 0x29, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x79, 0x72,
	0x65, 0x5f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x2f, 0x73, 0x70, 0x79, 0x72, 0x65, 0x5f, 0x68,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x80, 0x02, 0x0a, 0x06, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x44, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x12, 0x2c, 0x0a, 0x0a, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0c, 0x2e, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x0a, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2f, 0x0a, 0x0b, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d,
	0x2e, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x52, 0x0b, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x44, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x49, 0x44, 0x12, 0x44, 0x0a, 0x0f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0f, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x2c, 0x0a, 0x07,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x2a, 0x0a, 0x08, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x43, 0x49, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x43, 0x49, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2a, 0x3a, 0x0a, 0x0b, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x1b, 0x0a, 0x17, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x56, 0x46, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x50, 0x46,
	0x10, 0x02, 0x2a, 0x8c, 0x01, 0x0a, 0x0c, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x12, 0x1c, 0x0a, 0x18, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x46, 0x46, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x42, 0x4f, 0x4f, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x53,
	0x48, 0x55, 0x54, 0x54, 0x49, 0x4e, 0x47, 0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x03, 0x12, 0x0a,
	0x0a, 0x06, 0x4f, 0x4e, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x04, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x55,
	0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x5f, 0x44, 0x49, 0x41, 0x47, 0x4e, 0x4f, 0x53, 0x54, 0x49, 0x43,
	0x53, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10,
	0x06, 0x32, 0x59, 0x0a, 0x12, 0x53, 0x70, 0x79, 0x72, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x1d, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x53, 0x70, 0x79, 0x72, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x08, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x30, 0x01, 0x42, 0x12, 0x5a, 0x10,
	0x70, 0x6b, 0x67, 0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x2f, 0x73, 0x70, 0x79, 0x72, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_spyre_health_spyre_health_proto_rawDescOnce sync.Once
	file_pkg_proto_spyre_health_spyre_health_proto_rawDescData = file_pkg_proto_spyre_health_spyre_health_proto_rawDesc
)

func file_pkg_proto_spyre_health_spyre_health_proto_rawDescGZIP() []byte {
	file_pkg_proto_spyre_health_spyre_health_proto_rawDescOnce.Do(func() {
		file_pkg_proto_spyre_health_spyre_health_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_spyre_health_spyre_health_proto_rawDescData)
	})
	return file_pkg_proto_spyre_health_spyre_health_proto_rawDescData
}

var file_pkg_proto_spyre_health_spyre_health_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_proto_spyre_health_spyre_health_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_spyre_health_spyre_health_proto_goTypes = []interface{}{
	(DEVICE_TYPE)(0),              // 0: DEVICE_TYPE
	(DEVICE_STATE)(0),             // 1: DEVICE_STATE
	(*Device)(nil),                // 2: Device
	(*Devices)(nil),               // 3: Devices
	(*DeviceID)(nil),              // 4: DeviceID
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_pkg_proto_spyre_health_spyre_health_proto_depIdxs = []int32{
	4, // 0: Device.deviceID:type_name -> DeviceID
	0, // 1: Device.deviceType:type_name -> DEVICE_TYPE
	1, // 2: Device.deviceState:type_name -> DEVICE_STATE
	5, // 3: Device.updateTimestamp:type_name -> google.protobuf.Timestamp
	2, // 4: Devices.devices:type_name -> Device
	6, // 5: SpyreHealthService.RegisterForSpyreDevicesEvents:input_type -> google.protobuf.Empty
	3, // 6: SpyreHealthService.RegisterForSpyreDevicesEvents:output_type -> Devices
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_proto_spyre_health_spyre_health_proto_init() }
func file_pkg_proto_spyre_health_spyre_health_proto_init() {
	if File_pkg_proto_spyre_health_spyre_health_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_spyre_health_spyre_health_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Device); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_spyre_health_spyre_health_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Devices); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_spyre_health_spyre_health_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_spyre_health_spyre_health_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_spyre_health_spyre_health_proto_goTypes,
		DependencyIndexes: file_pkg_proto_spyre_health_spyre_health_proto_depIdxs,
		EnumInfos:         file_pkg_proto_spyre_health_spyre_health_proto_enumTypes,
		MessageInfos:      file_pkg_proto_spyre_health_spyre_health_proto_msgTypes,
	}.Build()
	File_pkg_proto_spyre_health_spyre_health_proto = out.File
	file_pkg_proto_spyre_health_spyre_health_proto_rawDesc = nil
	file_pkg_proto_spyre_health_spyre_health_proto_goTypes = nil
	file_pkg_proto_spyre_health_spyre_health_proto_depIdxs = nil
}
