// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: spyre_health.proto

package spyre

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DEVICE_TYPE defines the device type
type DEVICE_TYPE int32

const (
	DEVICE_TYPE_DEVICE_TYPE_UNSPECIFIED DEVICE_TYPE = 0 // Reserving message ID 0
	DEVICE_TYPE_VF                      DEVICE_TYPE = 1 // A VF device
	DEVICE_TYPE_PF                      DEVICE_TYPE = 2 // A PF device
)

// Enum value maps for DEVICE_TYPE.
var (
	DEVICE_TYPE_name = map[int32]string{
		0: "DEVICE_TYPE_UNSPECIFIED",
		1: "VF",
		2: "PF",
	}
	DEVICE_TYPE_value = map[string]int32{
		"DEVICE_TYPE_UNSPECIFIED": 0,
		"VF":                      1,
		"PF":                      2,
	}
)

func (x DEVICE_TYPE) Enum() *DEVICE_TYPE {
	p := new(DEVICE_TYPE)
	*p = x
	return p
}

func (x DEVICE_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DEVICE_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_spyre_health_proto_enumTypes[0].Descriptor()
}

func (DEVICE_TYPE) Type() protoreflect.EnumType {
	return &file_spyre_health_proto_enumTypes[0]
}

func (x DEVICE_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DEVICE_TYPE.Descriptor instead.
func (DEVICE_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_spyre_health_proto_rawDescGZIP(), []int{0}
}

// DEVICE_STATE defines the device state
type DEVICE_STATE int32

const (
	DEVICE_STATE_DEVICE_STATE_UNSPECIFIED DEVICE_STATE = 0 // Reserving message ID 0
	DEVICE_STATE_OFFLINE                  DEVICE_STATE = 1 // The device is in offline state, it has not been booted or it
	// has been shutdown
	DEVICE_STATE_BOOTING DEVICE_STATE = 2 // The device is in the booting (starting) state, with the
	// initialization being complete
	DEVICE_STATE_SHUTTING_DOWN       DEVICE_STATE = 3 // The device is in the process of shutting down
	DEVICE_STATE_ONLINE              DEVICE_STATE = 4 // The device initialization is complete
	DEVICE_STATE_RUNNING_DIAGNOSTICS DEVICE_STATE = 5 // The device is a running diagnostics
	DEVICE_STATE_IN_ERROR            DEVICE_STATE = 6 // The device is a non-running state
)

// Enum value maps for DEVICE_STATE.
var (
	DEVICE_STATE_name = map[int32]string{
		0: "DEVICE_STATE_UNSPECIFIED",
		1: "OFFLINE",
		2: "BOOTING",
		3: "SHUTTING_DOWN",
		4: "ONLINE",
		5: "RUNNING_DIAGNOSTICS",
		6: "IN_ERROR",
	}
	DEVICE_STATE_value = map[string]int32{
		"DEVICE_STATE_UNSPECIFIED": 0,
		"OFFLINE":                  1,
		"BOOTING":                  2,
		"SHUTTING_DOWN":            3,
		"ONLINE":                   4,
		"RUNNING_DIAGNOSTICS":      5,
		"IN_ERROR":                 6,
	}
)

func (x DEVICE_STATE) Enum() *DEVICE_STATE {
	p := new(DEVICE_STATE)
	*p = x
	return p
}

func (x DEVICE_STATE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DEVICE_STATE) Descriptor() protoreflect.EnumDescriptor {
	return file_spyre_health_proto_enumTypes[1].Descriptor()
}

func (DEVICE_STATE) Type() protoreflect.EnumType {
	return &file_spyre_health_proto_enumTypes[1]
}

func (x DEVICE_STATE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DEVICE_STATE.Descriptor instead.
func (DEVICE_STATE) EnumDescriptor() ([]byte, []int) {
	return file_spyre_health_proto_rawDescGZIP(), []int{1}
}

// Device defines an AIU device with its ID (PCI buses address),
// type (VF or PF), state and manager process id.
type Device struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeviceID         *DeviceID              `protobuf:"bytes,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`                          // The ID of the device
	DeviceType       DEVICE_TYPE            `protobuf:"varint,2,opt,name=deviceType,proto3,enum=DEVICE_TYPE" json:"deviceType,omitempty"`    // The type of device
	DeviceState      DEVICE_STATE           `protobuf:"varint,3,opt,name=deviceState,proto3,enum=DEVICE_STATE" json:"deviceState,omitempty"` // The device state
	ManagerProcessID int64                  `protobuf:"varint,4,opt,name=managerProcessID,proto3" json:"managerProcessID,omitempty"`         // Unix process id of the manager process
	UpdateTimestamp  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updateTimestamp,proto3" json:"updateTimestamp,omitempty"`            // The last state update timestamp
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_spyre_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_spyre_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_spyre_health_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetDeviceID() *DeviceID {
	if x != nil {
		return x.DeviceID
	}
	return nil
}

func (x *Device) GetDeviceType() DEVICE_TYPE {
	if x != nil {
		return x.DeviceType
	}
	return DEVICE_TYPE_DEVICE_TYPE_UNSPECIFIED
}

func (x *Device) GetDeviceState() DEVICE_STATE {
	if x != nil {
		return x.DeviceState
	}
	return DEVICE_STATE_DEVICE_STATE_UNSPECIFIED
}

func (x *Device) GetManagerProcessID() int64 {
	if x != nil {
		return x.ManagerProcessID
	}
	return 0
}

func (x *Device) GetUpdateTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTimestamp
	}
	return nil
}

// Devices defines a collection of devices
type Devices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Devices) Reset() {
	*x = Devices{}
	mi := &file_spyre_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Devices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Devices) ProtoMessage() {}

func (x *Devices) ProtoReflect() protoreflect.Message {
	mi := &file_spyre_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Devices.ProtoReflect.Descriptor instead.
func (*Devices) Descriptor() ([]byte, []int) {
	return file_spyre_health_proto_rawDescGZIP(), []int{1}
}

func (x *Devices) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

// DeviceID defines the device id (pci address)
type DeviceID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PCIAddress    string                 `protobuf:"bytes,1,opt,name=PCIAddress,proto3" json:"PCIAddress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceID) Reset() {
	*x = DeviceID{}
	mi := &file_spyre_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceID) ProtoMessage() {}

func (x *DeviceID) ProtoReflect() protoreflect.Message {
	mi := &file_spyre_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceID.ProtoReflect.Descriptor instead.
func (*DeviceID) Descriptor() ([]byte, []int) {
	return file_spyre_health_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceID) GetPCIAddress() string {
	if x != nil {
		return x.PCIAddress
	}
	return ""
}

var File_spyre_health_proto protoreflect.FileDescriptor

const file_spyre_health_proto_rawDesc = "" +
	"\n" +
	"\x12spyre_health.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x02\n" +
	"\x06Device\x12%\n" +
	"\bdeviceID\x18\x01 \x01(\v2\t.DeviceIDR\bdeviceID\x12,\n" +
	"\n" +
	"deviceType\x18\x02 \x01(\x0e2\f.DEVICE_TYPER\n" +
	"deviceType\x12/\n" +
	"\vdeviceState\x18\x03 \x01(\x0e2\r.DEVICE_STATER\vdeviceState\x12*\n" +
	"\x10managerProcessID\x18\x04 \x01(\x03R\x10managerProcessID\x12D\n" +
	"\x0fupdateTimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0fupdateTimestamp\",\n" +
	"\aDevices\x12!\n" +
	"\adevices\x18\x01 \x03(\v2\a.DeviceR\adevices\"*\n" +
	"\bDeviceID\x12\x1e\n" +
	"\n" +
	"PCIAddress\x18\x01 \x01(\tR\n" +
	"PCIAddress*:\n" +
	"\vDEVICE_TYPE\x12\x1b\n" +
	"\x17DEVICE_TYPE_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02VF\x10\x01\x12\x06\n" +
	"\x02PF\x10\x02*\x8c\x01\n" +
	"\fDEVICE_STATE\x12\x1c\n" +
	"\x18DEVICE_STATE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aOFFLINE\x10\x01\x12\v\n" +
	"\aBOOTING\x10\x02\x12\x11\n" +
	"\rSHUTTING_DOWN\x10\x03\x12\n" +
	"\n" +
	"\x06ONLINE\x10\x04\x12\x17\n" +
	"\x13RUNNING_DIAGNOSTICS\x10\x05\x12\f\n" +
	"\bIN_ERROR\x10\x062Y\n" +
	"\x12SpyreHealthService\x12C\n" +
	"\x1dRegisterForSpyreDevicesEvents\x12\x16.google.protobuf.Empty\x1a\b.Devices0\x01B\x12Z\x10pkg/health/spyreb\x06proto3"

var (
	file_spyre_health_proto_rawDescOnce sync.Once
	file_spyre_health_proto_rawDescData []byte
)

func file_spyre_health_proto_rawDescGZIP() []byte {
	file_spyre_health_proto_rawDescOnce.Do(func() {
		file_spyre_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spyre_health_proto_rawDesc), len(file_spyre_health_proto_rawDesc)))
	})
	return file_spyre_health_proto_rawDescData
}

var file_spyre_health_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_spyre_health_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spyre_health_proto_goTypes = []any{
	(DEVICE_TYPE)(0),              // 0: DEVICE_TYPE
	(DEVICE_STATE)(0),             // 1: DEVICE_STATE
	(*Device)(nil),                // 2: Device
	(*Devices)(nil),               // 3: Devices
	(*DeviceID)(nil),              // 4: DeviceID
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_spyre_health_proto_depIdxs = []int32{
	4, // 0: Device.deviceID:type_name -> DeviceID
	0, // 1: Device.deviceType:type_name -> DEVICE_TYPE
	1, // 2: Device.deviceState:type_name -> DEVICE_STATE
	5, // 3: Device.updateTimestamp:type_name -> google.protobuf.Timestamp
	2, // 4: Devices.devices:type_name -> Device
	6, // 5: SpyreHealthService.RegisterForSpyreDevicesEvents:input_type -> google.protobuf.Empty
	3, // 6: SpyreHealthService.RegisterForSpyreDevicesEvents:output_type -> Devices
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_spyre_health_proto_init() }
func file_spyre_health_proto_init() {
	if File_spyre_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spyre_health_proto_rawDesc), len(file_spyre_health_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spyre_health_proto_goTypes,
		DependencyIndexes: file_spyre_health_proto_depIdxs,
		EnumInfos:         file_spyre_health_proto_enumTypes,
		MessageInfos:      file_spyre_health_proto_msgTypes,
	}.Build()
	File_spyre_health_proto = out.File
	file_spyre_health_proto_goTypes = nil
	file_spyre_health_proto_depIdxs = nil
}
